# Generated by Django 3.2.13 on 2022-06-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='original',
            new_name='original_video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='processed',
            new_name='processed_video',
        ),
    ]
