# Generated by Django 3.2.13 on 2022-06-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220609_0024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='VideoModel',
        ),
    ]
