# Generated by Django 3.2.13 on 2022-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_video_videomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomodel',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='videomodel',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
